In [1]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operations

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [ ]:
arr2=a1+a2 
# size of array should be same for performing some operations
arr2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2 #float divison

array([0, 0, 0, 0, 0])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [9]:
l=[10,20,30,40]
arr=np.array(l)

In [ ]:
#l+10 # this is not possible
arr+10
 # agr apky multiple elements hai aur ap sary ky sary elements ko single element mein add krna chah rahye ho you will use broadcasting


array([20, 30, 40, 50])

In [11]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy


In [13]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [17]:
slice=slice*10
slice
# deep coppy vo hoti hai ky agr ap us mein koi changes kr rahye hain 
#to main array mein bi ho jaty hain jubky shallow coppy mein main array mein changes nai hoty

array([100, 200, 300, 400, 500])

In [ ]:
a[4:6]*10
a# a mein koi changes nai hain

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
# agr ap pury ky pury array ko coppy krty hain ksi mein to agr ap aik ky 
# andar koi changes kry gyein to automatically dusry mein bi ho jaye gyein
a
b=a.copy()
b[0]=99
b


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operation

In [24]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B # true way of multiplicating matrix
#A*B # wrong way of multiplicating matrix

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)
#since it is dot multiplication we can do it by this way

array([[19, 22],
       [43, 50]])

Transpose of Matrix

In [ ]:
A.T # row become column or column become row

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

stacking Array

In [31]:
# you can't stack mean combine two matrix

In [32]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:

np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
# column stack
np.column_stack((a,b))
# 1 dimensional nai rakhna 2 dimensional rakhna hai

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# advance arrays mein vectors ka use krna parta hai you cannot use matrix

Splitting array

In [40]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.hsplit(c,2)# split into two parts
# array split result in only equal division
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
# vertical split
a=np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
for i in a :
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
