In [10]:
import numpy as np


Basic Array creation

In [11]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
a=[1,2,3,4]
a


[1, 2, 3, 4]

In [13]:
np.array(a)

array([1, 2, 3, 4])

In [14]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l
# list is one dimensional

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l)
# two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function


In [16]:
#arange function is range function of array
arr=np.arange(1,11)
#1 sy ly kr 10 tak ka range ka array create hogaya
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# you can generate zero too
arr=np.zeros(6)
arr
arr1=np.zeros((4,8))#4 rows and 8 columns
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
arr=np.ones((1,2))
arr

array([[1., 1.]])

In [ ]:
# Linear Space
#numpy.linspace() is a function in NumPy that creates an array of evenly spaced numbers over a specified interval
#numpy.linspace(start, stop, num=50)
#start: Starting value of the sequence
#stop: Ending value of the sequence
#num: Number of samples to generate (default: 50)

# Create 5 evenly spaced numbers from 0 to 1
arr1 = np.linspace(0, 1, 5)
print(arr1)  # Output: [0.   0.25 0.5  0.75 1.  ]
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [43]:
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [ ]:


arr=np.linspace(0,1,100)
arr

[0.   0.25 0.5  0.75 1.  ]


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation Function

In [ ]:
import numpy as np
arr2=np.random.rand(10)
#aik square bracket laga ho start aur end mein to it is vector otherwise matrix
arr2 #This is concept of normalization  when value are between 1 and 0

array([0.57795154, 0.26091014, 0.49223481, 0.68454691, 0.15171859,
       0.69305615, 0.08125822, 0.09251026, 0.17817397, 0.33236959])

In [46]:
np.random.randn(10)
#standardization mein -3 to 3 value hoti hai

array([-0.02497755,  1.15834496, -0.18921197,  0.62450022,  1.70045248,
        1.48223347,  1.4402759 ,  0.38670466,  0.04793991, -1.06423391])

Array Attributes

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.shape


(3, 3)

In [49]:
arr.size

9

In [50]:
arr.dtype

dtype('int64')

Array Methods

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.min()

np.int64(1)

In [53]:
arr.max()

np.int64(9)

In [54]:
arr.sum()

np.int64(45)

In [55]:
np.sum(arr,axis=0)
#column wise sum

array([12, 15, 18])

In [56]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [57]:
arr.mean()

np.float64(5.0)

In [58]:
arr.std()

np.float64(2.581988897471611)

In [59]:
arr.argmax()
#give index of maximum element

np.int64(8)

In [60]:
arr.argmin()
#index of minimum element

np.int64(0)

Reshaping and Resizing

In [61]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
arr.reshape(5,4)#rows and columns should equal to total number of elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])