In [4]:
import numpy as np


NUMPY INDEXING AND SLICING OF VECTORS

In [5]:
arr1=np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr1[1]#12
arr1[1:5]
arr1[:5]#mean start from zero
arr1[1:]# mean end tak jana hai
arr1[3::2]#last one mean step

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [6]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#matrix of indexing is little different work on basis of rows and columns
#indexing of rows
arr[0]  
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
#indexing of columns
arr[0,0]#element on  0 row and 0 column is 1

np.int64(1)

In [ ]:
arr[0,4]
arr[5,4]#np.int64(30)

np.int64(30)

In [14]:
# slicing in matrix
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [17]:
#slicing 19,20,24,25,29,30
slice2=arr[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
# selecting column
arr[:,2]#puri rows +column
# jo bi slice kro gye vo column ki nai balky array ki hi form mein aye gyein

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [20]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
# getting even number
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [25]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])