Valid Sudoku


In [90]:
import numpy as np

In [91]:
s=np.array([ 
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
    ])

In [92]:
# sudoku mein row ka sum 45 hoga ,column ka bi 45 hoga

In [93]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [94]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [95]:
# if anyone have not 45 value then y sudoku is not valid

In [96]:
b=np.sum(s,axis=0)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [97]:
for i in b:
    if i !=45:
        print(f'Sudoku is not valid')
        break
    else:
        print('Sudoku is valid')

Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid
Sudoku is valid


In [98]:
c=np.sum(s,axis=1)
for i in c:
    if i !=45:
        print('column is not valid')
        break
    else:
        print('column is valid')

column is valid
column is valid
column is valid
column is valid
column is valid
column is valid
column is valid
column is valid
column is valid


In [99]:
d=s[0:3,0:3]
if d.sum == 45:
    print('Valid Sudoku')
else:
    print('invalid Sudoku')
d

invalid Sudoku


array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [100]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [101]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [102]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=(s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Question

In [103]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [104]:
# Get the shape of 
data.shape

(5, 3)

In [105]:
# Find the average age of student
np.mean(data[:,0])

np.float64(18.4)

In [106]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [107]:
#Find highest math marks
np.max(data[:,2])

np.int64(95)

In [108]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [109]:
##Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [110]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])


3

In [111]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [112]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [113]:
#Replace all Science marks < 75 with 0.
data[:,2] [data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])